<a href="https://colab.research.google.com/github/VishnuCodes96/capstone_projects/blob/main/capstone_project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# State-wise Renewable Energy Overview 2025–26

In [1]:
# Importing all the necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Data Source
 The information on this dataset is mainly taken from official sources for financial year 2025-26. However, in some cases, a few assumptions have been made and some data derived or assumed.

 `https://iced.niti.gov.in/analytics/state-wise-deep-dive`

 Copyright © 2026, NITI Aayog | India's Climate and Energy Dashboard

In [2]:
# importing the data
states = pd.read_csv('final_state-wise_renewable_energy_2025-26.csv')

## Step 1 - Exploring The Dataset

In [3]:
# Basic Checks
print(f'Number of rows in the dataset: {states.shape[0]}')
print(f'Number of columns in the dataset: {states.shape[1]}')
states.head()

Number of rows in the dataset: 18
Number of columns in the dataset: 11

,States,Capacity_By_Location,Capacity_Including_Allocated_Shares,Rooftop_Solar_Capacity,Generation,Peak_Demand,Hydro,Nuclear,Other_RES,Thermal,Population
0,Andhra Pradesh,31646.31,30419.54,774.5,98620.87,"14,011",3353.60,127.27,12690.11,14248.56,535.24
1,Telangana,19773.08,21852.44,695.9,73319.98,"18,548",2479.93,148.73,5524.98,13698.80,384.54
2,Tamil Nadu,47637.05,47618.83,1532.3,132210.74,"20,211",2203.20,1448.00,26954.38,17013.25,773.17
3,Haryana,8773.31,14845.56,1188.3,28032.91,"13,998",2490.83,123.04,3011.72,9219.97,309.36
4,Punjab,9119.93,14764.16,581.2,39557.58,"17,171",3827.44,229.09,2343.63,8364.00,311.22

In [4]:
states.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 11 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   States                               18 non-null     object
 1   Capacity_By_Location                 18 non-null     float64
 2   Capacity_Including_Allocated_Shares  18 non-null     float64
 3   Rooftop_Solar_Capacity               18 non-null     float64
 4   Generation                           18 non-null     float64
 5   Peak_Demand                          18 non-null     object
 6   Hydro                                18 non-null     float64
 7   Nuclear                              11 non-null     float64
 8   Other_RES                            18 non-null     float64
 9   Thermal                              18 non-null     float64
 10  Population                           18 non-null     float64
dtypes: float64(9), object(2)
memory usage: 1.7+ KB

In [5]:
states.describe().T

,count,mean,std,min,25%,50%,75%,max
Capacity_By_Location,18.0,23371.534444,22717.115333,83.49,7833.0200,14600.010,32926.0575,71690.64
Capacity_Including_Allocated_Shares,18.0,22704.162778,23230.257240,290.98,5083.1200,14804.860,30198.4750,70945.39
Rooftop_Solar_Capacity,18.0,1178.706111,1918.273642,6.68,110.2500,462.700,1114.5000,6881.80
Generation,18.0,80464.786111,61581.223729,65.25,30914.0775,75780.530,136208.1875,172616.73
Hydro,18.0,1654.768333,1319.286753,5.00,400.4750,1825.185,2488.1050,3827.44
Nuclear,11.0,514.150000,492.017539,41.68,131.4200,229.090,920.8150,1448.00
Other_RES,18.0,10392.831667,15617.522034,22.98,622.0325,2273.595,12004.4925,46608.04
Thermal,18.0,10342.360000,7954.774506,83.87,4059.0775,9209.655,14607.6525,27838.97
Population,18.0,553.236667,397.338755,15.90,309.8250,436.590,814.0675,1304.29

In [6]:
print(f'Number of null values: \n{states.isna().sum()}')

Number of null values:
States                                 0
Capacity_By_Location                   0
Capacity_Including_Allocated_Shares    0
Rooftop_Solar_Capacity                 0
Generation                             0
Peak_Demand                            0
Hydro                                  0
Nuclear                                7
Other_RES                              0
Thermal                                0
Population                             0
dtype: int64

In [7]:
print(f'Number of duplicated rows: {states.duplicated().sum()}')

Number of duplicated rows: 0

### Note
We can gather from the above executed cells that, there are 7 null values in the `Nuclear` column and no duplicated rows. The datatype in the `peak_demand` column is also not int64 or float64. So, we have to clean them, in order to perform further analysis.

## Step 2 - Cleaning The Dataset

In [8]:
clean_states_df = states.copy()

### Null values in `Nuclear` column
we can gather from different official data sources that there are no operational nuclear power plants in the states, that have null values, so filling it with mean or median, will distort the whole analysis. So, I decided to replace the null values to zero(0).

In [9]:
clean_states_df['Nuclear'] = clean_states_df['Nuclear'].fillna(0)
print(f'null values after cleaning Nuclear column: \n{clean_states_df.isna().sum()}')

null values after cleaning Nuclear column:
States                                 0
Capacity_By_Location                   0
Capacity_Including_Allocated_Shares    0
Rooftop_Solar_Capacity                 0
Generation                             0
Peak_Demand                            0
Hydro                                  0
Nuclear                                0
Other_RES                              0
Thermal                                0
Population                             0
dtype: int64

### Datatype in `Peak_demand` column
The datatype in Peak_Demand column moust be int64 or float64, to perform calculations on the column. So, I chose to remove ',' and change datatype as int64.

In [10]:
print(f'Peak_demand colum type before changing: {clean_states_df['Peak_Demand'].dtype}')
clean_states_df['Peak_Demand'] = clean_states_df['Peak_Demand'].str.replace(',','').astype(int)
print(f'Peak_demand colum type after changing: {clean_states_df['Peak_Demand'].dtype}')

Peak_demand colum type before changing: object
Peak_demand colum type after changing: int64

### Note
Before starting analysis I would like to do a regional analysis too. So I created a new column `Region`, to specify each state belongs to what region.

In [11]:
region_map = {
    "Andhra Pradesh" : "South",
    "Telangana" : "South",
    "Tamil Nadu" : "South",
    "Haryana" : "North",
    "Punjab" : "North",
    "Rajasthan" : "North",
    "Bihar" : "East",
    "Jharkhand" : "East",
    "Odisha" : "East",
    "West Bengal" : "East",
    "Goa" : "West",
    "Gujarat" : "West",
    "Maharashtra" : "West",
    "Arunachal Pradesh" : "North-East",
    "Assam" : "Nort-East",
    "Manipur" : "North-East",
    "Madhya Pradesh" : "Central",
    "Chhattisgarh" : "Central"
}

In [12]:
region_map_df = pd.DataFrame(list(region_map.items()),columns=["States","Region"])
region_map_df.head()

           States Region
0  Andhra Pradesh  South
1       Telangana  South
2      Tamil Nadu  South
3         Haryana  North
4          Punjab  North

In [13]:
state_region_merge_df = pd.merge(clean_states_df, region_map_df, on="States", how="left")
state_region_merge_df[['States','Region']].head()

           States Region
0  Andhra Pradesh  South
1       Telangana  South
2      Tamil Nadu  South
3         Haryana  North
4          Punjab  North

### Note
It's better to create a column named `Renewable_Energy`, because `Renewable_Energy = Hydro + Nuclear + Other_RES + Rooftop_Solar_Capacity`

In [14]:
state_region_merge_df['Renewable_Energy'] = (
    state_region_merge_df['Hydro'] +
    state_region_merge_df['Nuclear'] +
    state_region_merge_df['Other_RES'] +
    state_region_merge_df['Rooftop_Solar_Capacity']
)
state_region_merge_df[["States","Renewable_Energy"]].head()

           States  Renewable_Energy
0  Andhra Pradesh          16945.48
1       Telangana           8849.54
2      Tamil Nadu          32137.88
3         Haryana           6813.89
4          Punjab           6981.36

### Note
Before starting analysis we have to check whether the data has internal consistency. that can be checked, if the sum of values of columns `Hydro, Nuclear, Other_RES, Thermal` are equal to the column `Capacity_Including_Allocated_Shares`.

In [15]:
print(f'Number of rows that are in violation of internal consistency of the dataset: {
    (state_region_merge_df['Capacity_Including_Allocated_Shares'] != (
    state_region_merge_df['Hydro'] +
    state_region_merge_df['Nuclear'] +
    state_region_merge_df['Other_RES'] +
    state_region_merge_df['Thermal']
)).sum()
}')

Number of rows that are in violation of internal consistency of the dataset: 2

### Note
There are 2 rows that are violating the data internal consistency. So I cleaned it by replacing the values in the `Capacity_Including_Allocated_Shares` column in the foolowing manner.

In [16]:
state_region_merge_df['Capacity_Including_Allocated_Shares'] = (
    state_region_merge_df['Hydro'] +
    state_region_merge_df['Nuclear'] +
    state_region_merge_df['Other_RES'] +
    state_region_merge_df['Thermal']
)

# Checking After replacing the required column values
print(f'Number of rows that are in violation of internal consistency of the dataset after cleaning: {
    (state_region_merge_df['Capacity_Including_Allocated_Shares'] != (
    state_region_merge_df['Hydro'] +
    state_region_merge_df['Nuclear'] +
    state_region_merge_df['Other_RES'] +
    state_region_merge_df['Thermal']
)).sum()
}')

Number of rows that are in violation of internal consistency of the dataset after cleaning: 0

It's a good practice to save the cleaned dataset to a new file(.csv)

In [17]:
clean_states_df.to_csv("cleaned_state_wise_renewable_energy.csv", index=False)

## Step 3 - Analysis